"""Step 3 tests: team/parsing.py, team/taxonomy.py, team/nodes/extraction.py.

Run:
    pytest tests/test_team/test_extraction.py -v

No langgraph/fastmcp/litellm required for most of this file — extraction_node()
degrades to its deterministic fallback classifier whenever litellm isn't
installed or isn't configured, which is exactly the path this sandbox
exercises. The expected clause_type table below was generated by actually
running scripts/run_extraction.py and reading its output, not designed and
hoped for.

Step 10 made extraction_node() async and MCP-backed for the ONE thing it
didn't already have (contract_text pre-set): fetching contract text when the
caller hasn't loaded it already. Rather than make this whole file depend on
a live MCP server, the extraction_node name below is a test-local hermetic
wrapper that pre-populates contract_text from local disk before calling the
real async node — same "test the logic, don't depend on the flaky external
bit" hermeticity practice Steps 5-7 established for the LLM path. The real
MCP-fetch path itself has its own dedicated test further down, guarded with
pytest.importorskip("mcp").
"""
import asyncio
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO_ROOT))

from team.nodes.extraction import extraction_node as _extraction_node_async  # noqa: E402
from team.parsing import split_into_clauses  # noqa: E402
from team.scopes import AGENT_SCOPES  # noqa: E402
from team.state import seed_state  # noqa: E402
from team.taxonomy import CLAUSE_TYPES, classify_clause_type_fallback  # noqa: E402


def extraction_node(state):
    state = dict(state)
    if not state.get("contract_text"):
        state["contract_text"] = (REPO_ROOT / state["contract_path"]).read_text(encoding="utf-8")
    return asyncio.run(_extraction_node_async(state))

CONTRACTS_DIR = REPO_ROOT / "data" / "contracts"

# {filename: {clause_id: expected_clause_type_or_None}} — every clause in
# every M6 contract, confirmed against a real run of scripts/run_extraction.py.
EXPECTED_CLAUSE_TYPES = {
    "vendor_payments_processor_agreement.md": {
        "1.1": None, "2.1": None,
        "3.1": "refund_settlement_authority",
        "3.2": "refund_settlement_timing",
        "4.1": "termination_and_renewal",
        "5.1": "limitation_of_liability",
        "6.1": "indemnification",
        "7.1": "confidentiality_and_data_security",
        "8.1": "confidentiality_and_data_security",
        "9.1": "governing_law_and_venue",
        "10.1": "force_majeure",
    },
    "vendor_fulfillment_logistics_agreement.md": {
        "1.1": None,
        "2.1": "delivery_sla_alignment",
        "3.1": "delay_compensation_alignment",
        "4.1": "lost_in_transit_threshold",
        "5.1": "disputed_delivery_investigation",
        "6.1": "carrier_liability_cap",
        "7.1": None,
        "8.1": "termination_and_renewal",
        "9.1": "force_majeure",
    },
    "vendor_warranty_repair_partner_agreement.md": {
        "1.1": None,
        "2.1": "repair_turnaround",
        "2.2": "replacement_turnaround",
        "3.1": "warranty_void_criteria_alignment",
        "3.2": "repair_vs_replacement_decision_authority",
        "4.1": None,
        "5.1": "claim_status_reporting_cadence",
        "6.1": None,
        "7.1": "termination_and_renewal",
        "8.1": "confidentiality_and_data_security",
    },
    "vendor_returns_processing_agreement.md": {
        "1.1": None,
        "2.1": "return_intake_window",
        "2.2": "condition_grading_alignment",
        "2.3": "category_exclusions",
        "3.1": "inspection_to_refund_buffer",
        "4.1": "return_mishandling_liability",
        "5.1": None, "6.1": None,
        "7.1": "termination_and_renewal",
    },
}


# ---------------------------------------------------------------------------
# team/parsing.py
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("filename,expected", list(EXPECTED_CLAUSE_TYPES.items()))
def test_split_into_clauses_matches_expected_clause_ids(filename, expected):
    text = (CONTRACTS_DIR / filename).read_text(encoding="utf-8")
    clauses = split_into_clauses(text)
    assert [c["clause_id"] for c in clauses] == list(expected.keys())


def test_split_into_clauses_bodies_are_nonempty_and_exclude_the_header():
    text = (CONTRACTS_DIR / "vendor_payments_processor_agreement.md").read_text(encoding="utf-8")
    clauses = split_into_clauses(text)
    for c in clauses:
        assert c["body"], f"clause {c['clause_id']} has an empty body"
        assert "**" not in c["body"].splitlines()[0], (
            f"clause {c['clause_id']}'s body still contains its own header line"
        )


# ---------------------------------------------------------------------------
# team/taxonomy.py
# ---------------------------------------------------------------------------

def test_every_clause_type_is_used_by_at_least_one_contract_clause():
    """A taxonomy entry the corpus never exercises is dead weight — this
    catches a typo in CLAUSE_TYPES or CLAUSE_TYPE_KEYWORDS that would
    otherwise silently go untested."""
    used = {
        clause_type
        for contract in EXPECTED_CLAUSE_TYPES.values()
        for clause_type in contract.values()
        if clause_type is not None
    }
    assert used == set(CLAUSE_TYPES)


@pytest.mark.parametrize(
    "filename,clause_id,expected_type",
    [
        (fname, cid, ctype)
        for fname, clauses in EXPECTED_CLAUSE_TYPES.items()
        for cid, ctype in clauses.items()
    ],
)
def test_fallback_classifier_matches_expected_clause_type(filename, clause_id, expected_type):
    text = (CONTRACTS_DIR / filename).read_text(encoding="utf-8")
    clauses = {c["clause_id"]: c for c in split_into_clauses(text)}
    title = clauses[clause_id]["title"]
    assert classify_clause_type_fallback(title) == expected_type


# ---------------------------------------------------------------------------
# team/nodes/extraction.py — extraction_node()
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("filename,expected", list(EXPECTED_CLAUSE_TYPES.items()))
def test_extraction_node_end_to_end_per_contract(filename, expected):
    state = seed_state(f"data/contracts/{filename}")
    result = extraction_node(state)

    assert result["contract_text"], "extraction must load and return the contract text"
    assert len(result["clauses"]) == len(expected)
    for clause in result["clauses"]:
        want = expected[clause["clause_id"]] or "unclassified"
        assert clause["clause_type"] == want, (
            f"{filename} clause {clause['clause_id']}: "
            f"expected {want!r}, got {clause['clause_type']!r}"
        )
        assert clause["text"], f"{filename} clause {clause['clause_id']} has empty text"


def test_extraction_node_output_stays_inside_its_write_scope():
    state = seed_state("data/contracts/vendor_payments_processor_agreement.md")
    result = extraction_node(state)
    allowed = AGENT_SCOPES["extraction"] | {"log"}
    assert set(result) <= allowed, f"extraction wrote outside its scope: {set(result) - allowed}"


def test_extraction_node_logs_one_line_per_clause_plus_a_summary_line():
    state = seed_state("data/contracts/vendor_returns_processing_agreement.md")
    result = extraction_node(state)
    assert len(result["log"]) == len(result["clauses"]) + 1


def test_extraction_node_reuses_contract_text_already_in_state():
    """If contract_text is already populated (e.g. a caller pre-loaded it, or
    a future MCP-backed node set it), extraction must not re-read the file —
    it should just parse what's already there."""
    real_text = (CONTRACTS_DIR / "vendor_payments_processor_agreement.md").read_text(
        encoding="utf-8"
    )
    tampered_text = real_text.replace(
        "**3.1 Refund Settlement Authority**", "**3.1 Renamed For This Test**"
    )
    state = seed_state("data/contracts/does_not_exist_on_disk.md", contract_text=tampered_text)
    result = extraction_node(state)
    titles = {c["clause_id"]: c["title"] for c in result["clauses"]}
    assert titles["3.1"] == "Renamed For This Test"


def test_extraction_node_fetches_via_mcp_when_contract_text_is_unset():
    """The real Step 10 integration point, exercised for real (not the
    hermetic wrapper above): when contract_text is NOT pre-set,
    extraction_node must fetch it through the MCP contract-repository
    server (mcp_server/contract_server.py) rather than reading local disk
    directly. Skips cleanly if mcp isn't installed wherever this runs."""
    pytest.importorskip("mcp", reason="mcp SDK not installed in this environment")
    from team.nodes.extraction import extraction_node as real_extraction_node

    state = seed_state("data/contracts/vendor_payments_processor_agreement.md")
    assert not state["contract_text"]  # sanity: this test only means something if unset

    result = asyncio.run(real_extraction_node(state))
    on_disk = (CONTRACTS_DIR / "vendor_payments_processor_agreement.md").read_text(encoding="utf-8")
    assert result["contract_text"] == on_disk
    assert len(result["clauses"]) == len(EXPECTED_CLAUSE_TYPES["vendor_payments_processor_agreement.md"])