"""Step 4 tests: team/bm25.py, team/policy_corpus.py, team/playbook_index.py,
team/nodes/playbook_rag.py.

Run:
    pytest tests/test_team/test_playbook_rag.py -v

No langgraph/fastmcp/litellm required for most of this file — everything
here is plain Python retrieval over local files. The EXPECTED_FINDINGS table
below was generated by actually running scripts/run_playbook_rag.py end to
end and reading its (corrected) output, not designed and hoped for — see
Step 4's build notes for the two real bugs this caught along the way.

Step 10 made extraction_node() and playbook_rag_node() async and MCP-backed
(contract text and the negotiation playbook now come from
mcp_server/contract_server.py rather than local disk). Rather than make
this whole file depend on a live MCP server, both names below are
test-local hermetic wrappers: extraction_node pre-populates contract_text
from local disk before calling the real async node, and playbook_rag's
module-level positions cache is primed directly from a local disk parse
before any test runs, so playbook_rag_node's own _positions() call never
reaches MCP either. Same "test the logic, don't depend on the flaky
external bit" practice Steps 5-7 established for the LLM path. The real
MCP-fetch paths have their own dedicated tests in test_extraction.py and
test_mcp_server.py, guarded with pytest.importorskip("mcp").
"""
import asyncio
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO_ROOT))

from team.bm25 import BM25, tokenize  # noqa: E402
from team.nodes.extraction import extraction_node as _extraction_node_async  # noqa: E402
from team.nodes.playbook_rag import playbook_rag_node as _playbook_rag_node_async  # noqa: E402
import team.nodes.playbook_rag as _playbook_rag_module  # noqa: E402
from team.playbook_index import (  # noqa: E402
    CLAUSE_TYPE_TO_PLAYBOOK_CLAUSE,
    PLAYBOOK_PATH,
    load_playbook_positions,
    parse_playbook_positions,
)
from team.policy_corpus import CHUNKERS, load_policy_corpus  # noqa: E402
from team.scopes import AGENT_SCOPES  # noqa: E402
from team.state import seed_state  # noqa: E402
from team.taxonomy import CLAUSE_TYPES  # noqa: E402

# Prime playbook_rag's module-level positions cache directly from a local
# disk parse, once, before any test runs -- so _positions() never needs to
# reach the MCP server during this file's run.
_playbook_rag_module._POSITIONS_CACHE = parse_playbook_positions(
    PLAYBOOK_PATH.read_text(encoding="utf-8")
)


def extraction_node(state):
    state = dict(state)
    if not state.get("contract_text"):
        state["contract_text"] = (REPO_ROOT / state["contract_path"]).read_text(encoding="utf-8")
    return asyncio.run(_extraction_node_async(state))


def playbook_rag_node(state):
    return asyncio.run(_playbook_rag_node_async(state))

# {filename: {clause_id: {...}}} — the exact, corrected output of a real
# end-to-end run. "skipped" entries are unclassified clauses; everything
# else records whether a playbook position was found, whether it produced
# any retrieved policy passages, and (if so) the single top match.
EXPECTED_FINDINGS = {
    "vendor_payments_processor_agreement.md": {
        "1.1": {"status": "skipped"},
        "2.1": {"status": "skipped"},
        "3.1": {"playbook_clause": "1.1", "has_passages": True,
                "top_doc": "refund-authority.md"},
        "3.2": {"playbook_clause": "1.2", "has_passages": True,
                "top_doc": "returns-policy.md"},
        "4.1": {"playbook_clause": "5.1", "has_passages": False},
        "5.1": {"playbook_clause": "5.2", "has_passages": False},
        "6.1": {"playbook_clause": "5.3", "has_passages": False},
        "7.1": {"playbook_clause": "5.5", "has_passages": False},
        "8.1": {"playbook_clause": "5.5", "has_passages": False},
        "9.1": {"playbook_clause": "5.4", "has_passages": False},
        "10.1": {"playbook_clause": "5.6", "has_passages": True,
                 "top_doc": "shipping-policy.md"},
    },
    "vendor_fulfillment_logistics_agreement.md": {
        "1.1": {"status": "skipped"},
        "2.1": {"playbook_clause": "2.1", "has_passages": True,
                "top_doc": "shipping-policy.md"},
        "3.1": {"playbook_clause": "2.2", "has_passages": True,
                "top_doc": "shipping-policy.md"},
        "4.1": {"playbook_clause": "2.3", "has_passages": True,
                "top_doc": "shipping-policy.md"},
        "5.1": {"playbook_clause": "2.4", "has_passages": True,
                "top_doc": "shipping-policy.md"},
        "6.1": {"playbook_clause": "2.5", "has_passages": False},
        "7.1": {"status": "skipped"},
        "8.1": {"playbook_clause": "5.1", "has_passages": False},
        "9.1": {"playbook_clause": "5.6", "has_passages": True,
                "top_doc": "shipping-policy.md"},
    },
    "vendor_warranty_repair_partner_agreement.md": {
        "1.1": {"status": "skipped"},
        "2.1": {"playbook_clause": "3.1", "has_passages": True,
                "top_doc": "warranty-policy.md"},
        "2.2": {"playbook_clause": "3.2", "has_passages": True,
                "top_doc": "warranty-policy.md"},
        "3.1": {"playbook_clause": "3.3", "has_passages": True,
                "top_doc": "warranty-policy.md"},
        "3.2": {"playbook_clause": "3.4", "has_passages": True,
                "top_doc": "warranty-policy.md", "top_section": "5.1"},
        "4.1": {"status": "skipped"},
        "5.1": {"playbook_clause": "3.5", "has_passages": True,
                "top_doc": "warranty-policy.md"},
        "6.1": {"status": "skipped"},
        "7.1": {"playbook_clause": "5.1", "has_passages": False},
        "8.1": {"playbook_clause": "5.5", "has_passages": False},
    },
    "vendor_returns_processing_agreement.md": {
        "1.1": {"status": "skipped"},
        "2.1": {"playbook_clause": "4.1", "has_passages": True,
                "top_doc": "returns-policy.md"},
        "2.2": {"playbook_clause": "4.2", "has_passages": True,
                "top_doc": "returns-policy.md"},
        "2.3": {"playbook_clause": "4.3", "has_passages": True,
                "top_doc": "returns-policy.md"},
        "3.1": {"playbook_clause": "4.4", "has_passages": True,
                "top_doc": "returns-policy.md"},
        "4.1": {"playbook_clause": "4.5", "has_passages": False},
        "5.1": {"status": "skipped"},
        "6.1": {"status": "skipped"},
        "7.1": {"playbook_clause": "5.1", "has_passages": False},
    },
}

CONTRACTS_DIR = REPO_ROOT / "data" / "contracts"


def _run_full_playbook_rag(contract_filename: str) -> dict:
    """Extraction, then playbook_rag_node driven one clause per call until
    every clause has a finding — the same loop scripts/run_playbook_rag.py
    uses. Returns the final state dict."""
    state = dict(seed_state(f"data/contracts/{contract_filename}"))
    state.update(extraction_node(state))
    for _ in range(len(state["clauses"])):
        update = playbook_rag_node(state)
        state["playbook_findings"] = state["playbook_findings"] + update.get("playbook_findings", [])
        state["log"] = state["log"] + update.get("log", [])
    return state


# ---------------------------------------------------------------------------
# team/bm25.py
# ---------------------------------------------------------------------------

def test_tokenize_strips_punctuation():
    assert tokenize("Refund settlement authority?!") == [
        "refund", "settlement", "authority"
    ]


def test_bm25_ranks_the_relevant_document_first():
    docs = [
        "delivery service level agreement metro non-metro business days",
        "warranty repair turnaround ten business days",
        "the quick brown fox jumps over the lazy dog",
    ]
    bm25 = BM25(docs)
    hits = bm25.search("delivery service level")
    assert hits[0][0] == 0


def test_bm25_search_excludes_zero_score_documents():
    bm25 = BM25(["alpha beta gamma", "delta epsilon zeta"])
    hits = bm25.search("nonexistent term entirely")
    assert hits == []


def test_bm25_search_respects_top_k():
    docs = [f"shared term {i}" for i in range(10)]
    bm25 = BM25(docs)
    hits = bm25.search("shared term", top_k=3)
    assert len(hits) == 3


# ---------------------------------------------------------------------------
# team/policy_corpus.py
# ---------------------------------------------------------------------------

def test_load_policy_corpus_covers_all_5_docs():
    chunks = load_policy_corpus()
    docs_seen = {c["doc"] for c in chunks}
    assert docs_seen == set(CHUNKERS)


def test_load_policy_corpus_chunk_counts_match_verified_run():
    chunks = load_policy_corpus()
    counts = {}
    for c in chunks:
        counts[c["doc"]] = counts.get(c["doc"], 0) + 1
    assert counts == {
        "refund-authority.md": 4,
        "returns-policy.md": 8,
        "shipping-policy.md": 7,
        "warranty-policy.md": 17,
        "escalation-tone.md": 10,
    }


def test_every_chunk_has_the_required_fields():
    for chunk in load_policy_corpus():
        assert set(chunk) == {"doc", "section_id", "heading", "body"}
        assert chunk["heading"]


def test_some_warranty_chunks_have_empty_bodies_by_design():
    """warranty-policy.md's '## N. Title' parent headers (e.g. '## 5.
    Replacement vs. Repair Decision Rule') have no direct body text of their
    own — their content lives entirely under their '### N.N' children. This
    is expected, not a parsing bug — see the empty-body exclusion in
    playbook_rag._policy_index()."""
    warranty_chunks = [c for c in load_policy_corpus() if c["doc"] == "warranty-policy.md"]
    empty = [c for c in warranty_chunks if not c["body"]]
    # sections 2, 3, 4, 5, 6, 7 are pure '## N. Title' parents whose content
    # lives entirely under their '### N.N' children; only section 1
    # (Introduction) has body text directly under its '##' heading.
    assert len(empty) == 6


# ---------------------------------------------------------------------------
# team/playbook_index.py
# ---------------------------------------------------------------------------

def test_every_clause_type_resolves_to_a_playbook_position():
    positions = load_playbook_positions()
    assert set(positions) == set(CLAUSE_TYPES) == set(CLAUSE_TYPE_TO_PLAYBOOK_CLAUSE)


def test_clause_type_to_playbook_clause_mapping_matches_the_real_file():
    """Regression guard for the explicit (not zip-derived) mapping: every
    entry must point at a clause number that actually exists in the real
    playbook file."""
    from team.parsing import split_into_clauses

    text = (REPO_ROOT / "data" / "playbook" / "negotiation-playbook.md").read_text(
        encoding="utf-8"
    )
    real_clause_ids = {c["clause_id"] for c in split_into_clauses(text)}
    for clause_type, clause_number in CLAUSE_TYPE_TO_PLAYBOOK_CLAUSE.items():
        assert clause_number in real_clause_ids, (
            f"{clause_type} maps to playbook clause {clause_number}, "
            f"which no longer exists in negotiation-playbook.md"
        )


def test_refund_settlement_authority_position_has_all_three_tiers():
    positions = load_playbook_positions()
    parts = positions["refund_settlement_authority"]["parts"]
    assert set(parts) == {"preferred", "fallback", "unacceptable"}
    assert "INR 2,000" in parts["preferred"]
    assert "USD 50" in parts["unacceptable"]


def test_governing_law_position_uses_the_note_label():
    positions = load_playbook_positions()
    assert "note" in positions["governing_law_and_venue"]["parts"]


def test_confidentiality_position_uses_the_acceptable_as_is_label():
    positions = load_playbook_positions()
    assert "acceptable_as_is" in positions["confidentiality_and_data_security"]["parts"]


def test_positions_with_no_policy_citation_have_empty_cited_docs():
    """These 6 playbook clauses are pure negotiation stances — they cite no
    internal policy doc, on purpose (see negotiation-playbook.md)."""
    positions = load_playbook_positions()
    for clause_type in (
        "termination_and_renewal", "limitation_of_liability", "indemnification",
        "governing_law_and_venue", "confidentiality_and_data_security",
        "carrier_liability_cap", "return_mishandling_liability",
    ):
        assert positions[clause_type]["cited_docs"] == []


# ---------------------------------------------------------------------------
# team/nodes/playbook_rag.py
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("filename", list(EXPECTED_FINDINGS))
def test_playbook_rag_end_to_end_per_contract(filename):
    state = _run_full_playbook_rag(filename)
    expected = EXPECTED_FINDINGS[filename]

    assert len(state["playbook_findings"]) == len(state["clauses"])
    by_id = {f["clause_id"]: f for f in state["playbook_findings"]}

    for clause_id, want in expected.items():
        got = by_id[clause_id]
        if want.get("status") == "skipped":
            assert got["status"] == "skipped"
            continue

        assert got["status"] == "found"
        assert got["position"]["clause_number"] == want["playbook_clause"]
        has_passages = bool(got["retrieved_passages"])
        assert has_passages == want["has_passages"], (
            f"{filename} clause {clause_id}: expected has_passages="
            f"{want['has_passages']}, got {has_passages}"
        )
        if want["has_passages"]:
            top = got["retrieved_passages"][0]
            assert top["doc"] == want["top_doc"]
            if "top_section" in want:
                assert top["section_id"] == want["top_section"]


def test_playbook_rag_processes_exactly_one_clause_per_call():
    state = dict(seed_state("data/contracts/vendor_payments_processor_agreement.md"))
    state.update(extraction_node(state))
    update = playbook_rag_node(state)
    assert len(update["playbook_findings"]) == 1


def test_playbook_rag_no_ops_once_everything_is_done():
    state = _run_full_playbook_rag("vendor_payments_processor_agreement.md")
    update = playbook_rag_node(state)
    assert "playbook_findings" not in update
    assert "nothing outstanding" in update["log"][0]


def test_playbook_rag_output_stays_inside_its_write_scope():
    state = dict(seed_state("data/contracts/vendor_payments_processor_agreement.md"))
    state.update(extraction_node(state))
    update = playbook_rag_node(state)
    allowed = AGENT_SCOPES["playbook_rag"] | {"log"}
    assert set(update) <= allowed


def test_playbook_rag_never_returns_an_empty_body_passage():
    """Regression test for the first bug this step caught: a header-only
    chunk (empty body) must never appear as a retrieved passage — there's
    nothing in it to ground a citation in."""
    for filename in EXPECTED_FINDINGS:
        state = _run_full_playbook_rag(filename)
        for finding in state["playbook_findings"]:
            for passage in finding.get("retrieved_passages", []):
                assert passage["snippet"], (
                    f"{filename} clause {finding['clause_id']} retrieved an "
                    f"empty-body passage: {passage['doc']} §{passage['section_id']}"
                )


def test_playbook_rag_never_retrieves_from_an_uncited_document():
    """Regression test for the second bug: when a playbook position cites
    specific docs, every retrieved passage must come from one of them —
    never a same-worded chunk from an unrelated policy file."""
    for filename in EXPECTED_FINDINGS:
        state = _run_full_playbook_rag(filename)
        for finding in state["playbook_findings"]:
            if finding["status"] != "found":
                continue
            cited = set(finding["position"]["cited_docs"])
            if not cited:
                assert finding["retrieved_passages"] == []
                continue
            for passage in finding["retrieved_passages"]:
                assert passage["doc"] in cited


def test_playbook_rag_node_fetches_playbook_via_mcp_when_cache_is_cold():
    """The real Step 10 integration point, exercised for real (not the
    hermetic module-cache priming above): with a genuinely cold
    _POSITIONS_CACHE, playbook_rag_node must fetch the negotiation playbook
    through the MCP server (mcp_server/contract_server.py's
    contracts://playbook/negotiation resource) and parse it into the same
    positions a local disk read would produce. Skips cleanly if mcp isn't
    installed wherever this runs."""
    pytest.importorskip("mcp", reason="mcp SDK not installed in this environment")
    from team.nodes.playbook_rag import playbook_rag_node as real_playbook_rag_node

    saved_cache = _playbook_rag_module._POSITIONS_CACHE
    _playbook_rag_module._POSITIONS_CACHE = None  # force a real MCP fetch
    try:
        state = dict(seed_state("data/contracts/vendor_payments_processor_agreement.md"))
        state["contract_text"] = (
            CONTRACTS_DIR / "vendor_payments_processor_agreement.md"
        ).read_text(encoding="utf-8")
        state.update(asyncio.run(_extraction_node_async(state)))

        # The first clause(s) may be "unclassified" (this contract's 1.1 and
        # 2.1 both are), in which case playbook_rag_node returns early
        # WITHOUT ever calling _positions() -- caught by an earlier version
        # of this test asserting fetched_positions after only one call and
        # getting None back. Loop until a real lookup actually happens.
        for _ in range(len(state["clauses"])):
            update = asyncio.run(real_playbook_rag_node(state))
            state["playbook_findings"] = state["playbook_findings"] + update.get("playbook_findings", [])
            if _playbook_rag_module._POSITIONS_CACHE is not None:
                break

        fetched_positions = _playbook_rag_module._POSITIONS_CACHE
        assert fetched_positions is not None, "no classified clause ever triggered a real lookup"
        assert fetched_positions == load_playbook_positions()
    finally:
        _playbook_rag_module._POSITIONS_CACHE = saved_cache  # restore for later tests